### PR TITLE
feat: adds support for vw, vh unit for maxHeight, maxWidth

### LINKED ISSUE #525: Support for vw, vh unit for maxWidth, maxHeight
### Overview of the problem

I'm using re-resizable 6.0.0

My **browser** is:  Chrome
   
I am sure this issue is **not a duplicate**? Not sure

### Description
re-resizable currently supports defaultSize property related to the viewport, it will be helpful if maxWidth and maxHeight can also be assigned relative to viewport.e.g. maxHeight="90vw"

### Steps to Reproduce
Please refer the link below

https://codesandbox.io/s/admiring-violet-tqi45

### Expected behavior
component should not resize when the width of component is more than 90% of the viewport.

### Actual behavior
maxHeight ending with % is being handled currently. but when it ends with vw or vh it breaks

### PR DESCRIPTION
**Pull request by hhvys**
resolves #525

### CODE REVIEW

**Comment by bokuweb** [comment]
@hhvys Sorry, could you update README.md too?

**Comment by hhvys** [comment]
> Great :) if you are ok, could you please add test case with vh/vw?

Sorry, test will require #content value in fixture.html to change. If possible merge without test.
Thanks

**Comment by bokuweb** [comment]
@hhvys Thanks. I see. Ok Please could you update update only README? if done I'll merge it :)

**Comment by bokuweb** [comment]
@hhvys v6.1.0 just published :tada: Thanks for your work

**Pull request merged**
