### PR TITLE
bugfix: calculate parent height even when the parent is a flex container

### LINKED ISSUE #764: [BUG] re-resizable with minHeight set in "%" does not work
Bug

### Overview of the problem

I'm using re-resizable **version** [6.9.2]   
   

My **browser** is:   chrome
   
I am sure this issue is **not a duplicate**.

### Description

Re-resizable fails to calculate parent size when 
 * display: "flex",
 *  flexDirection: "column"
 
styles are set on the parent DOM.
As a result, "maxHeight" props cannot be set in %.

This is simply because an inappropriate css style is set for "base" DOM-element:
https://codepen.io/shin-t/pen/WNdbGjm
it shrinks to zero as "flex-basis" style defaults to zero when you set it via "flex".
https://developer.mozilla.org/ja/docs/Web/CSS/flex

### Steps to Reproduce

1. First Step
2. Second Step
3. and so on...

See the codepen below:
https://codesandbox.io/s/re-resizable-bug-behavior-f3grus?file=/src/index.tsx

Drag-and-drop the lower boundary of resizable region.

### Expected behavior

The resizable region resizes in vertical direction

### Actual behavior

The resizable region resizes to zero height.
This buggy behavior fixes when I pass maxHeight in pixel or vh.

### PR DESCRIPTION
**Pull request by shinToita**
### Proposed solution

Fixes #764

### Tradeoffs

None.

### Testing Done

I have confirmed that this fix works.

### CODE REVIEW

**Comment by bokuweb** [comment]
@shinToita Thanks for your PR. LGTM

**Comment by shinToita** [comment]
hmm... It looks to me that an older version (without this fix) is published on npm as v6.9.3.
Can you kindly take a look at it, please?

**Comment by bokuweb** [comment]
@shinToita Oops. sorry, I repulbished. please try 6.9.5.

**Comment by shinToita** [comment]
Thx! I confirmed the version include the fix.

**Pull request merged**
