### PR TITLE
Match focus order to visual order

### PR DESCRIPTION
**Pull request by t-hamano**
### Proposed solution

Thank you for providing an amazing library.

I'm a member of [the Gutenberg project](https://github.com/WordPress/gutenberg) (part of WordPress) and provide our own [`ResizableBox` component](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/resizable-box) that wraps this library.

Our own component supports the same props as the library, and additionally renders a focusable button element via the `handleComponent` prop to allow the user to focus the resizer and resize it via keyboard events ([Example](https://github.com/WordPress/gutenberg/blob/8e795580bdd03724f0a894a34418ea58e208b3e3/packages/edit-post/src/components/layout/index.js#L357)).

I noticed that because the `Resizer` components are always rendered together _after_ its `children`, sometimes the focus order doesn't match the visual order.

This PR splits the `renderResizer()` into before and after the `children`, which should make the focus order and visual order match.

### Testing Done

I've created a temporary story to test this PR, and if it makes sense I'd like to delete it after you review it.

The URL for the storybook is http://localhost:6066/?path=/story/handle--multiple.

The video below shows how pressing the tab key moves focus when children contains focusable elements:

#### Before

https://github.com/user-attachments/assets/97e3be72-783f-4904-9993-e4c507be6bea

#### After

https://github.com/user-attachments/assets/ff989f7f-efe6-4733-92e5-57ebde9fb76c

### CODE REVIEW

**Comment by bokuweb** [comment]
@t-hamano Thanks for your great work. 
However test is failed now, could you please check it 🙏 
https://github.com/bokuweb/re-resizable/actions/runs/10962662887/job/30466650429?pr=827

**Comment by t-hamano** [comment]
Thanks for the review! I should have run the unit tests locally before submitting the PR 😅

The unit test was failing because splitting the resizer increased the number of divs by one:

### Before

before

### After

after

Therefore, it seems the test fails because the number of actual `div` elements doesn't match the number of `divs` the `toBe()` matcher expects.

The increase in the number of divs was intentional, so I fixed the test itself.

For the same reason, the second `div`, `(await divs.all())[1]`, is no longer a resizer. So it also needs to be increased by one.

Please let me know if I've missed anything.

**Comment by bokuweb** [comment]
@t-hamano Looks great!! thanks for your contribution :)

**Comment by bokuweb** [comment]
6.10.0 published

**Pull request merged**
