### PR TITLE
Fixes #175 allow 0 as minWidth and minHeight

### LINKED ISSUE #175: impossible to set minWidth to 0
### Overview of the problem

I'm using re-resizable **version** [4.2.1]   

### Description

Setting a minimumsize to 0 will result in the minimum size to be 10px, ref this line: https://github.com/bokuweb/re-resizable/blob/master/src/index.js#L411

Why is this limitation set?

### Expected behavior

That the element should be allowed to resize to 0px

### Actual behavior

Minimum size is 10px

### PR DESCRIPTION
**Pull request by hbogs**
### Testing Done
I have tried getting the tests to run, but eventually gave up - so I have NOT been able to run the tests on my machine (Windows env)...

### CODE REVIEW

**Comment by bokuweb** [comment]
@hbogs Thanks for your PR :) LGTM 👍

**Comment by bokuweb** [comment]
close #175

**Comment by bokuweb** [comment]
@hbogs v4.3.0 published

**Comment by hbogs** [comment]
Thanks :)

**Pull request merged**
